### ISSUE TITLE
Creating HTML Page

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/node-basics#32]
### Goal
We don't want to return dummy HTML content to the user when the hit a certain route. But instead we want to render real HTML files. For that we are going to create a folder called views in which we are going to put all of our HTML files created.

### Tasks

- [x] create a folder we call **_views_**
- [x] create inside the _views_ folder two HTML files called **_shop.html_** and **_add-product.html_**
- [x] in _add-product.html_, use the vs-code to create HTML 5 skeleton, change title of the page to **Add Product**.
- [x] In the body of add-product page create a form to add a product. But also we create a navigation bar that will allow us to navigate back and forth from add-product page to shop page and other way around.
- [x] In the body  of shop page, copy over the navigation bar and in the <main> section we display the list of dummy products.
