### ISSUE TITLE
Serving HTML Page

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/node-basics#34]
### Goal

We want to serve the shop and add-product pages in the routes. 

### Tasks

- [x] In the **routes/shop.js** file, in the **`GET '/'`**  handler middleware, replace send() by sendFile()
- [x] import the **path** module from the node core modules and use path.join()  with __dirname global variable to have the handle on the html files in the views folder
- [x] repeat the same process to render add-product page
- [x] create _**404.html**_ HTML page for a 404 error page in the _views_ folder
- [x] in the middleware tasked to render an error message whenever we don't have a matching route handler middleware, we  send the 404.html file using sendFile and path module.

**Comment by OpenTechConsult** [comment]
We have made a mistake by pushing the commit to the main branch.
We are trying to revert the process
