### ISSUE TITLE
Elegantly referencing a file when using sendFile

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/node-basics#37]
### Goals

We want a cleaner and an elegant way of referencing file when using res.sendFile.
We want to get the current directory by using a little helper function.

### Tasks

- [ ] create a folder called utils. 
- [ ] inside utils folder, create a file called path.js file
- [ ] in path.js create the logic to get the current directory of the app.js
