### ISSUE TITLE
Adding Controllers

### ISSUE THREAD

**Issue by OpenTechConsult** [OpenTechConsult/node-basics#63]
### Goals

We want to implement the MVC pattern in our project so that we have a clear separation of concerns. For that, we want to extract the page rendering logic out of the router code to the controllers that we will create.

### Tasks 

- [ ]  `products.js` and `errors.js` controller files inside the `controllers` folder in the root directory
- [ ]  in `/routes/admin.js`, extract the `(req, res, next) => {...}` callback function responsible for rendering the `add-product` page from the `router.get('/add-product', ...)` route hander  and place it inside the `product.js` controller file and export the function under the `getAddProduct` name using `exports.xxx` syntax.
- [ ] still in `/routes/admin.js`, extract the `(req, res, next) => {...}` callback function responsible for posting the form product data to the server and storing that data in an array
- [ ] in the` /routes/shop.js`, extract the callback function responsible for rendering the `shop.ejs` page (which is displayed at the root of the project) and place that function inside the products.js controller file under the `getProducts` name/
- [ ] extracted the fallback middleware function that executes when no route is matched to a controller file aka errors.js
